version: '2'
services:
  suitecrm:
    build: src
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      -  ${PWD}/upload:/var/www/html/upload
      -  ${PWD}/config.php:/var/www/html/config.php
    environment:
      DB_TYPE: mysql
      DB_MANAGER: MysqlManager

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qnPBgFbTh63NJcPT9xofax6hjBD9JG
      MYSQL_DATABASE: suitecrm
      MYSQL_USER: suitecrm
      MYSQL_PASSWORD: 9rt3tCxHH9WvuN8FXyiPxcmbnN7iTC

volumes:
  mysqldata:
